{
    "name": "Loan Management System",
    "version": "19.0.9.0.0",
    "summary": "End-to-end customer loan lifecycle management",
    "category": "Accounting/Accounting",
    "author": "Custom",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": ["mail", "account", "website", "portal", "crm","hr_attendance"],
    "data": [
        "security/loan_security.xml",
        "security/ir.model.access.csv",
        "data/loan_sequence.xml",
        'data/email_template.xml',
        "report/loan_agreement_report.xml",
        "report/loan_operational_reports.xml",
        "report/loan_dashboard_report.xml",
        "report/loan_payment_reciept_report.xml",
        "report/loan_disbursement_report.xml",
        "report/loan_installment_schedule_report.xml",
        "views/crm_lead_loan_views.xml",
        "views/loan_type_views.xml",
        "views/loan_dashboard_views.xml",
        "views/loan_dashboard_client_action.xml",
        "views/loan_views.xml",
        "views/loan_installment_views.xml",
        "views/loan_payment_views.xml",
        "views/loan_disbursement_views.xml",
        "views/loan_payment_register_views.xml",
        "wizard/loan_disburse_wizard_views.xml",
        "wizard/loan_foreclose_wizard_views.xml",
        "wizard/loan_collection_report_wizard_views.xml",
        "views/loan_proofs_views.xml",
        "views/loan_config_master_views.xml",
        "views/loan_menus.xml",
        "views/website/loan_portal_templates.xml",

    ],
    "application": True,
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "loan_management_system/static/src/js/loan_dashboard_client_action.js",
            "loan_management_system/static/src/xml/loan_dashboard_templates.xml",
            "loan_management_system/static/src/scss/loan_dashboard.scss",
        ],
    },
}
